name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build & Sign Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Normalize line endings for Gradle wrapper
        run: |
          sudo apt-get update
          sudo apt-get install -y dos2unix
          dos2unix ./gradlew

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Decode release.keystore
        env:
          KEYSTORE_FILE_BASE64: ${{ secrets.KEYSTORE_FILE_BASE64 }}
        run: |
          echo "$KEYSTORE_FILE_BASE64" | base64 --decode > release.keystore

      - name: Set signing env vars
        env:
          KEYSTORE_PATH:      ${{ runner.workspace }}/release.keystore
          KEYSTORE_PASSWORD:  ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS:          ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD:       ${{ secrets.KEY_PASSWORD }}
        run: echo "Signing env vars are set"

      # ─────────────────────────────────────────────────────────
      - name: Build signed release APK
        run: ./gradlew assembleRelease

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk